[package]
name = "fsae-raspi"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
socketcan = {version = "3.3.0", features = ["tokio"]}
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }
influxdb = { version = "0.7.2", features = ["derive"] }